require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DownSizesController do

  # This should return the minimal set of attributes required to create a valid
  # DownSize. As you add validations to DownSize, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all down_sizes as @down_sizes" do
      down_size = DownSize.create! valid_attributes
      get :index
      assigns(:down_sizes).should eq([down_size])
    end
  end

  describe "GET show" do
    it "assigns the requested down_size as @down_size" do
      down_size = DownSize.create! valid_attributes
      get :show, :id => down_size.id
      assigns(:down_size).should eq(down_size)
    end
  end

  describe "GET new" do
    it "assigns a new down_size as @down_size" do
      get :new
      assigns(:down_size).should be_a_new(DownSize)
    end
  end

  describe "GET edit" do
    it "assigns the requested down_size as @down_size" do
      down_size = DownSize.create! valid_attributes
      get :edit, :id => down_size.id
      assigns(:down_size).should eq(down_size)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DownSize" do
        expect {
          post :create, :down_size => valid_attributes
        }.to change(DownSize, :count).by(1)
      end

      it "assigns a newly created down_size as @down_size" do
        post :create, :down_size => valid_attributes
        assigns(:down_size).should be_a(DownSize)
        assigns(:down_size).should be_persisted
      end

      it "redirects to the created down_size" do
        post :create, :down_size => valid_attributes
        response.should redirect_to(DownSize.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved down_size as @down_size" do
        # Trigger the behavior that occurs when invalid params are submitted
        DownSize.any_instance.stub(:save).and_return(false)
        post :create, :down_size => {}
        assigns(:down_size).should be_a_new(DownSize)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DownSize.any_instance.stub(:save).and_return(false)
        post :create, :down_size => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested down_size" do
        down_size = DownSize.create! valid_attributes
        # Assuming there are no other down_sizes in the database, this
        # specifies that the DownSize created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DownSize.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => down_size.id, :down_size => {'these' => 'params'}
      end

      it "assigns the requested down_size as @down_size" do
        down_size = DownSize.create! valid_attributes
        put :update, :id => down_size.id, :down_size => valid_attributes
        assigns(:down_size).should eq(down_size)
      end

      it "redirects to the down_size" do
        down_size = DownSize.create! valid_attributes
        put :update, :id => down_size.id, :down_size => valid_attributes
        response.should redirect_to(down_size)
      end
    end

    describe "with invalid params" do
      it "assigns the down_size as @down_size" do
        down_size = DownSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DownSize.any_instance.stub(:save).and_return(false)
        put :update, :id => down_size.id, :down_size => {}
        assigns(:down_size).should eq(down_size)
      end

      it "re-renders the 'edit' template" do
        down_size = DownSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DownSize.any_instance.stub(:save).and_return(false)
        put :update, :id => down_size.id, :down_size => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested down_size" do
      down_size = DownSize.create! valid_attributes
      expect {
        delete :destroy, :id => down_size.id
      }.to change(DownSize, :count).by(-1)
    end

    it "redirects to the down_sizes list" do
      down_size = DownSize.create! valid_attributes
      delete :destroy, :id => down_size.id
      response.should redirect_to(down_sizes_url)
    end
  end

end
