require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForecastWsizesController do

  # This should return the minimal set of attributes required to create a valid
  # ForecastWsize. As you add validations to ForecastWsize, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all forecast_wsizes as @forecast_wsizes" do
      forecast_wsize = ForecastWsize.create! valid_attributes
      get :index
      assigns(:forecast_wsizes).should eq([forecast_wsize])
    end
  end

  describe "GET show" do
    it "assigns the requested forecast_wsize as @forecast_wsize" do
      forecast_wsize = ForecastWsize.create! valid_attributes
      get :show, :id => forecast_wsize.id
      assigns(:forecast_wsize).should eq(forecast_wsize)
    end
  end

  describe "GET new" do
    it "assigns a new forecast_wsize as @forecast_wsize" do
      get :new
      assigns(:forecast_wsize).should be_a_new(ForecastWsize)
    end
  end

  describe "GET edit" do
    it "assigns the requested forecast_wsize as @forecast_wsize" do
      forecast_wsize = ForecastWsize.create! valid_attributes
      get :edit, :id => forecast_wsize.id
      assigns(:forecast_wsize).should eq(forecast_wsize)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ForecastWsize" do
        expect {
          post :create, :forecast_wsize => valid_attributes
        }.to change(ForecastWsize, :count).by(1)
      end

      it "assigns a newly created forecast_wsize as @forecast_wsize" do
        post :create, :forecast_wsize => valid_attributes
        assigns(:forecast_wsize).should be_a(ForecastWsize)
        assigns(:forecast_wsize).should be_persisted
      end

      it "redirects to the created forecast_wsize" do
        post :create, :forecast_wsize => valid_attributes
        response.should redirect_to(ForecastWsize.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forecast_wsize as @forecast_wsize" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastWsize.any_instance.stub(:save).and_return(false)
        post :create, :forecast_wsize => {}
        assigns(:forecast_wsize).should be_a_new(ForecastWsize)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastWsize.any_instance.stub(:save).and_return(false)
        post :create, :forecast_wsize => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forecast_wsize" do
        forecast_wsize = ForecastWsize.create! valid_attributes
        # Assuming there are no other forecast_wsizes in the database, this
        # specifies that the ForecastWsize created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ForecastWsize.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => forecast_wsize.id, :forecast_wsize => {'these' => 'params'}
      end

      it "assigns the requested forecast_wsize as @forecast_wsize" do
        forecast_wsize = ForecastWsize.create! valid_attributes
        put :update, :id => forecast_wsize.id, :forecast_wsize => valid_attributes
        assigns(:forecast_wsize).should eq(forecast_wsize)
      end

      it "redirects to the forecast_wsize" do
        forecast_wsize = ForecastWsize.create! valid_attributes
        put :update, :id => forecast_wsize.id, :forecast_wsize => valid_attributes
        response.should redirect_to(forecast_wsize)
      end
    end

    describe "with invalid params" do
      it "assigns the forecast_wsize as @forecast_wsize" do
        forecast_wsize = ForecastWsize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastWsize.any_instance.stub(:save).and_return(false)
        put :update, :id => forecast_wsize.id, :forecast_wsize => {}
        assigns(:forecast_wsize).should eq(forecast_wsize)
      end

      it "re-renders the 'edit' template" do
        forecast_wsize = ForecastWsize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ForecastWsize.any_instance.stub(:save).and_return(false)
        put :update, :id => forecast_wsize.id, :forecast_wsize => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forecast_wsize" do
      forecast_wsize = ForecastWsize.create! valid_attributes
      expect {
        delete :destroy, :id => forecast_wsize.id
      }.to change(ForecastWsize, :count).by(-1)
    end

    it "redirects to the forecast_wsizes list" do
      forecast_wsize = ForecastWsize.create! valid_attributes
      delete :destroy, :id => forecast_wsize.id
      response.should redirect_to(forecast_wsizes_url)
    end
  end

end
