require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HeightsController do

  # This should return the minimal set of attributes required to create a valid
  # Height. As you add validations to Height, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all heights as @heights" do
      height = Height.create! valid_attributes
      get :index
      assigns(:heights).should eq([height])
    end
  end

  describe "GET show" do
    it "assigns the requested height as @height" do
      height = Height.create! valid_attributes
      get :show, :id => height.id
      assigns(:height).should eq(height)
    end
  end

  describe "GET new" do
    it "assigns a new height as @height" do
      get :new
      assigns(:height).should be_a_new(Height)
    end
  end

  describe "GET edit" do
    it "assigns the requested height as @height" do
      height = Height.create! valid_attributes
      get :edit, :id => height.id
      assigns(:height).should eq(height)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Height" do
        expect {
          post :create, :height => valid_attributes
        }.to change(Height, :count).by(1)
      end

      it "assigns a newly created height as @height" do
        post :create, :height => valid_attributes
        assigns(:height).should be_a(Height)
        assigns(:height).should be_persisted
      end

      it "redirects to the created height" do
        post :create, :height => valid_attributes
        response.should redirect_to(Height.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved height as @height" do
        # Trigger the behavior that occurs when invalid params are submitted
        Height.any_instance.stub(:save).and_return(false)
        post :create, :height => {}
        assigns(:height).should be_a_new(Height)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Height.any_instance.stub(:save).and_return(false)
        post :create, :height => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested height" do
        height = Height.create! valid_attributes
        # Assuming there are no other heights in the database, this
        # specifies that the Height created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Height.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => height.id, :height => {'these' => 'params'}
      end

      it "assigns the requested height as @height" do
        height = Height.create! valid_attributes
        put :update, :id => height.id, :height => valid_attributes
        assigns(:height).should eq(height)
      end

      it "redirects to the height" do
        height = Height.create! valid_attributes
        put :update, :id => height.id, :height => valid_attributes
        response.should redirect_to(height)
      end
    end

    describe "with invalid params" do
      it "assigns the height as @height" do
        height = Height.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Height.any_instance.stub(:save).and_return(false)
        put :update, :id => height.id, :height => {}
        assigns(:height).should eq(height)
      end

      it "re-renders the 'edit' template" do
        height = Height.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Height.any_instance.stub(:save).and_return(false)
        put :update, :id => height.id, :height => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested height" do
      height = Height.create! valid_attributes
      expect {
        delete :destroy, :id => height.id
      }.to change(Height, :count).by(-1)
    end

    it "redirects to the heights list" do
      height = Height.create! valid_attributes
      delete :destroy, :id => height.id
      response.should redirect_to(heights_url)
    end
  end

end
